name: Security Scan (Trivy & Grype)

on:
  workflow_run:
    workflows: ["Docker Build and Artifact Export"]
    types:
      - completed

jobs:
  security-scan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Trivy & Grype Vulnerability Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract short SHA
        id: vars
        run: echo "sha_short=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Load Docker image from previous workflow
        uses: actions/download-artifact@v4
        with:
          name: docker-image-${{ env.sha_short }}
          path: .

      - name: Load image into Docker
        run: |
          gunzip -c docker-image-${{ env.sha_short }}.tar.gz > image.tar
          docker load -i image.tar

      ################################
      #        TRIVY SCAN           #
      

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Trivy image scan (JSON report)
        run: |
          trivy image \
            --scanners vuln \
            --format json \
            --output trivy-report.json \
            local/app:${{ env.sha_short }} || true

      - name: Upload Trivy JSON report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report-${{ env.sha_short }}
          path: trivy-report.json

      ################################
      #        GRYPE SCAN           #
      

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | \
            sudo sh -s -- -b /usr/local/bin

      - name: Grype image scan (JSON report)
        run: |
          grype \
            local/app:${{ env.sha_short }} \
            -o json > grype-report.json || true

      - name: Upload Grype JSON report
        uses: actions/upload-artifact@v4
        with:
          name: grype-report-${{ env.sha_short }}
          path: grype-report.json